version: "3"

services:

  arachni:
    build: .
    depends_on:
      - postgres
    ports:
      - "9292:9292"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=arachni
      - POSTGRES_DB=arachni_production
